import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[var(--card-bg)] text-[var(--card-text)] antialiased">
        {/* Top Navbar */}
        <header className="flex items-center justify-between px-6 h-16 border-b border-[var(--card-border)] bg-[var(--card-header-bg)]">
          <span className="font-bold tracking-wider text-[var(--card-accent)]">VLAD</span>
          <nav className="flex gap-4 text-sm font-medium">
            <a href="/" className="hover:text-[var(--card-accent)] transition-colors">Home</a>
          </nav>
        </header>

        {/* Main page content renders here */}
        <main>{children}</main>
      </body>
    </html>
  );
}